language: node_js
node_js:
  - "12"

addons:
  sonarcloud:
    organization: 'ynov'
    token:
      secure: 'ZCCxuDMZRMFRmkxVbDmbSOQ+swlt39oh7yB4ujns0R/p0L/gCmlsd1gRe6ddf9MLxAlT/oEOPE7DZvSrS3DxiX0dz+zgiNQJKKHaGfNWOviutxa++4TRlwE3wpCJFWXf7QIt+UgSCEZ/3siugKNLtTCt4SMqKNxJGOW2SDwTWXwnoD5xs46/nMjCyhQCzRJ0j51aePuCpcVIv78OhBzl6i8QpCzGSpPj9vSAE/4qgC5Xj4IUWUKYlo7UsXW5Z5G2XWNNz4Gb4g6807wU1Mx0MEwCQJmaqePPi1R0y7IX5Zv1ZxRCp6IgoOvBKvPo3tEaHcU37XPD51RvvlkP14Ynht+cGAZk5GX2vcJ7WGUulM+/xz0XJv9ZiAZqWXPhGVQCEC/0bQ0hTGVxWIJUZJ0nMgQDg6EFygz3kpgUl1EvtTgdwdaV8/7qE26+XIjMfqGAoqKmR+QtqUnmBP1ftjPdn4j0P20fFzcA6zs/dKrqrrYicpa9X/haA58Aq3XO657O0f33uU+J+9/3xiuHUzNYmjc+94jA3JfRZQ8y6T70ZN6Y/THujB8OvGCaJCtQydCtTSIP2/EnLdrPYP8kRXBj0BT3x4LweKJFr4GQOJ781hWiApmrjh+KScDwgg71rqZXZKQsWkkE5AHLlCudtfp7U0db7pEM+paZKpnzg0UjtTo='
jobs:
  include:
    - stage: build docker image
      script:
      - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - docker build -t front .
      - docker tag front $DOCKER_USER/front
      - docker push $DOCKER_USER/front
    - stage: test
      script: 
        - sonar-scanner
        - docker run --rm $DOCKER_USER/front node_modules/react-scripts/bin/react-scripts.js test --watchAll=false
    