language: node_js
node_js:
  - "12"

addons:
  sonarcloud:
    organization: 'ynov'
    token:
      secure: "GxGSrgF4Qv3fNM9ttnEQvXiRjVwoEaTO9MK/cihvTfcZxFegvsTxtVbRqZVJEG26s2qtwVPOuYzRrTf+ekhEkRos7VgXPVdQahs8rU+s4Ie/lZ2xIChXTHDzMRIWk6y7MaWezspoO00vhGw52RP0fO7ItjtdwvImB7BmS5d94Am8AtUZrxxz3CtLXUZ9bO6I3NWsMa1sI/fVKGB+Blg4zqBXw4PBUPQ6a3svKXYmKaMTxGgIufUxOHkN61Y7o60/yCdKhf9An9mhcxOdr20Pg+v8QVGPR2cB+kBZLEs0X3FCX730DEy94cnYKGbdOS4ITBoV0vT8yPBMX7VHuk7k3DWWQke99QAx3GEiD1g6bVV9kQhkiZChu5GUZEhFALf722fhBRD2cpxbN/DJt8DqOYTFik3SQw7Y1QfYc8DY0DyRme2ikT6pGSNB1PJH8p0yWgT3oJ5nUqSKLMCC6y5o9m8WCRhPxd3sgzIJubNoN4G1v5tHqzU4wb1+hxKCGe7m+10gtX4/g+Kh/dP4v2NiCBltz7kPG9O5BfhSVij2wmU5GpMOqUgH+IjKrAwU4oVEsMkpcp3za8q9tec7zxSy1M3USA9fqqF+Wze1omA+XjeBWL4GJ1eDjqXYhp2GosdOOvNagPpmzbVM2nHmQ1HOZz9GfzWr3p82e6TmTjrZw6w="
jobs:
  include:
    - stage: build docker image
      script:
      - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - docker build -t front .
      - docker tag front $DOCKER_USER/front
      - docker push $DOCKER_USER/front
    - stage: test
      script: 
        - sonar-scanner
        - docker run --rm $DOCKER_USER/front node_modules/react-scripts/bin/react-scripts.js test --watchAll=false
    