export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
export const GET_CATEGORIES = 'GET_CATEGORIES';
export const GET_CATEGORIES_ERROR = 'GET_CATEGORIES_ERROR';

export const FETCH_CATEGORY = 'FETCH_CATEGORY';
export const GET_CATEGORY = 'GET_CATEGORY';
export const GET_CATEGORY_ERROR = 'GET_CATEGORY_ERROR';
export const INIT_CATEGORY = 'INIT_CATEGORY';

export const FETCH_TOP_CATEGORIES = 'FETCH_TOP_CATEGORIES';
export const GET_TOP_CATEGORIES = 'GET_TOP_CATEGORIES';
export const GET_TOP_CATEGORIES_ERROR = 'GET_TOP_CATEGORIES_ERROR';
